tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask "1password"
cask "calibre"
cask "google-drive"
cask "grandperspective"
cask "iina"
cask "notion"
cask "selfcontrol"
cask "spotify"
cask "visual-studio-code"

tap "homebrew/cask-versions"
cask "transmission-beta"

tap "homebrew/cask-drivers"
cask "logi-options-plus"

tap "arielrezinn/custom"
cask "open-in-vs-code"
cask "open-terminal-here"